package com.laa.model.civil.enums;

public enum IncomeType {
	
	CHILD_BENEFIT,
	INCAPACITY_BENEFIT,
	CARER_ALLOWANCE,
	HOUSING_BENEFIT,
	MAINTENANCE,
  CHILD_TAX_CREDIT,  
  MISCELLANEOUS,
  MAINTENANCE_INCOME

}
