package com.acme.mypackage;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.3
 * 2018-03-23T16:31:35.465Z
 * Generated source version: 3.2.3
 *
 */
@WebServiceClient(name = "CaseServices_ep",
                  wsdlLocation = "file:/Users/asrahussain/digital/workspace/case-model/src/main/resources/Schema/BusinessServices/CCMS/CaseManagement/CaseServices.wsdl",
                  targetNamespace = "http://legalservices.gov.uk/CCMS/CaseManagement/Case/1.0/CaseServices")
public class CaseServicesEp extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://legalservices.gov.uk/CCMS/CaseManagement/Case/1.0/CaseServices", "CaseServices_ep");
    public final static QName CaseServicesPt = new QName("http://legalservices.gov.uk/CCMS/CaseManagement/Case/1.0/CaseServices", "CaseServices_pt");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/asrahussain/digital/workspace/case-model/src/main/resources/Schema/BusinessServices/CCMS/CaseManagement/CaseServices.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CaseServicesEp.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/Users/asrahussain/digital/workspace/case-model/src/main/resources/Schema/BusinessServices/CCMS/CaseManagement/CaseServices.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CaseServicesEp(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CaseServicesEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CaseServicesEp() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CaseServicesEp(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CaseServicesEp(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CaseServicesEp(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CaseServices
     */
    @WebEndpoint(name = "CaseServices_pt")
    public CaseServices getCaseServicesPt() {
        return super.getPort(CaseServicesPt, CaseServices.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CaseServices
     */
    @WebEndpoint(name = "CaseServices_pt")
    public CaseServices getCaseServicesPt(WebServiceFeature... features) {
        return super.getPort(CaseServicesPt, CaseServices.class, features);
    }

}
