package com.acme.mypackage;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.3
 * 2018-03-23T16:31:35.433Z
 * Generated source version: 3.2.3
 *
 */
@WebService(targetNamespace = "http://legalservices.gov.uk/CCMS/CaseManagement/Case/1.0/CaseServices", name = "CaseServices")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CaseServices {

    @WebMethod(operationName = "GetCaseDetails", action = "http://legalservices.gov.uk/CCMS/CaseManagement/Case/1.0/CaseServices/GetCaseDetails")
    @WebResult(name = "CaseInqRS", targetNamespace = "http://legalservices.gov.uk/CCMS/CaseManagement/Case/1.0/CaseBIM", partName = "payload")
    public CaseInqRS getCaseDetails(
        @WebParam(partName = "payload", name = "CaseInqRQ", targetNamespace = "http://legalservices.gov.uk/CCMS/CaseManagement/Case/1.0/CaseBIM")
        CaseInqRQ payload
    );

    @WebMethod(operationName = "UpdateCase", action = "http://legalservices.gov.uk/CCMS/CaseManagement/Case/1.0/CaseServices/UpdateCase")
    @WebResult(name = "CaseUpdateRS", targetNamespace = "http://legalservices.gov.uk/CCMS/CaseManagement/Case/1.0/CaseBIM", partName = "payload")
    public CaseUpdateRS updateCase(
        @WebParam(partName = "payload", name = "CaseUpdateRQ", targetNamespace = "http://legalservices.gov.uk/CCMS/CaseManagement/Case/1.0/CaseBIM")
        CaseUpdateRQ payload
    );

    @WebMethod(operationName = "CreateCaseApplication", action = "http://legalservices.gov.uk/CCMS/CaseManagement/Case/1.0/CaseServices/CreateCaseApplication")
    @WebResult(name = "CaseAddRS", targetNamespace = "http://legalservices.gov.uk/CCMS/CaseManagement/Case/1.0/CaseBIM", partName = "payload")
    public CaseAddRS createCaseApplication(
        @WebParam(partName = "payload", name = "CaseAddRQ", targetNamespace = "http://legalservices.gov.uk/CCMS/CaseManagement/Case/1.0/CaseBIM")
        CaseAddRQ payload
    );

    @WebMethod(operationName = "GetCaseTxnStatus", action = "http://legalservices.gov.uk/CCMS/CaseManagement/Case/1.0/CaseServices/GetCaseTxnStatus")
    @WebResult(name = "CaseAddUpdtStatusRS", targetNamespace = "http://legalservices.gov.uk/CCMS/CaseManagement/Case/1.0/CaseBIM", partName = "payload")
    public CaseAddUpdtStatusRS getCaseTxnStatus(
        @WebParam(partName = "payload", name = "CaseAddUpdtStatusRQ", targetNamespace = "http://legalservices.gov.uk/CCMS/CaseManagement/Case/1.0/CaseBIM")
        CaseAddUpdtStatusRQ payload
    );

    @WebMethod(operationName = "GetAssessmentData", action = "http://legalservices.gov.uk/CCMS/CaseManagement/Case/1.0/CaseServices/GetAssessmentData")
    @WebResult(name = "GetAssessmentDataRS", targetNamespace = "http://legalservices.gov.uk/CCMS/CaseManagement/Case/1.0/CaseBIM", partName = "payload")
    public GetAssessmentDataRS getAssessmentData(
        @WebParam(partName = "payload", name = "GetAssessmentDataRQ", targetNamespace = "http://legalservices.gov.uk/CCMS/CaseManagement/Case/1.0/CaseBIM")
        GetAssessmentDataRQ payload
    );
}
